[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "main.rs"
name = "desktop"

[dependencies.titanium]
path = "../../"
features = [
    "desktop-gui",
]

[dependencies]
# add your dependencies here
