[package]
name = "titanium_keybinds"
version = "1.0.0-alpha.1"
edition = "2021"

[dependencies.titaniumutils]
package = "titanium_utils"
default-features = false
path = "../utils"
features = [
    "macros"
]

[dependencies]
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
once_cell = "1.9.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
