[package]
name = "titanium_keybinds"
version = "1.0.0-alpha.2"
edition = "2021"

[dependencies.titaniumutils]
package = "titanium_utils"
default-features = false
path = "../utils"
features = [
    "macros"
]

[dependencies]
strum = { version = "0.24.0", features = ["derive"] }
strum_macros = "0.24.0"
once_cell = "1.9.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

[target.'cfg(target_os="linux")'.dependencies]
libc = "0.2.113"
input = "0.7.1"
nix = "0.24.1"
x11 = { version = "2.19.1", features = ["xlib", "xtest"] }
uinput = { version = "0.1.3", default-features = false }
