[package]
name = "titanium"
version = "1.0.0-alpha.2"
edition = "2021"

[lib]
path = "titanium/lib.rs"

[workspace]
members = [
    "titanium/desktop",
    "titanium/web",
]

[dependencies.titaniummacros]
path = "./titanium/macros"
package = "macros"
optional = true

[dependencies.async-std]
features = ["attributes"]
version = "1.12"
optional = true

[dependencies.titaniumutils]
path = "./titanium/desktop/utils"
package = "titanium_utils"
default-features = false
features = ["macros"]

[dependencies.titaniumdesktop]
path = "./titanium/desktop"
package = "titanium_desktop"
optional = true

[dependencies.titaniumweb]
path = "./titanium/web"
package = "titanium_web"
optional = true

[features]
default = ["macros"]

macros = ["titaniummacros", "async-std"]

desktop = ["titaniumdesktop"]
desktop-gui = ["desktop", "titaniumdesktop/gui"]
desktop-full = ["desktop", "desktop-gui", "titaniumdesktop/full", "macros"]

web = ["titaniumweb"]
web-socket = ["web", "titaniumweb/socket"]
web-full = ["web", "web-socket", "titaniumweb/full", "macros"]
