[package]
name = "web"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "main.rs"
name = "web"

[dependencies.titanium]
features = [
    "web",
    "web-full"
]
path = "../../"

[dependencies]
# add your dependencies here
