[package]
name = "example_web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "example_web"
path = "main.rs"

[dependencies.titanium]
features = [
    "web-full"
]
path = "../../"

[dependencies]
# add your dependencies here
