[package]
name = "web"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["."]

[[bin]]
path = "main.rs"
name = "web"

[dependencies.titanium]
features = ["web-full"]
path = "../../"

[dependencies]
# add your dependencies here
