[package]
name = "titanium_web"
version = "1.0.0-alpha.4"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
async-std = { version = "1.12", features = ["attributes"] }
tide-websockets = "0.4"
tide = "0.16"

[features]
socket = []
full = ["socket"]
