[package]
name = "titanium_web"
version = "1.0.0-alpha.1"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
tide-websockets = "0.4.0"
tide = "0.16.0"

[features]
full = []