[package]
name = "macros"
version = "1.0.0-alpha.3"
edition = "2021"

[lib]
name = "macros"
path = "lib.rs"
proc-macro = true

[dependencies.quote]
version = "1"

[dependencies.syn]
version = "2"
features = ["full"]
