[package]
name = "titanium_desktop_discord"
version = "1.0.0-alpha.5"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.8", features = ["v4"] }