name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [
            ubuntu-latest,
            windows-latest,
            macos-latest
          ]
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Install Dependencies
        run: ./epearl installDeps
      - name: Build
        run: ./epearl build full

  clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt
      - name: Run rust-clippy
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true