name: Doc

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Common Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Install Dependencies
        run: sudo apt-get install libgtk-3-dev libsdl-pango-dev libx11-dev libxtst-dev libudev-dev libinput-dev -y
      - name: Build
        run: cargo build --workspace --all-features

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - run: cargo doc --workspace --no-deps
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './target/doc/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1